name: warung_ajib
description: Aplikasi UMKM Warung Ajib

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/es_teh_ajib.png
    - assets/images/lumpia.png
    - assets/images/jajanan.png
    - assets/images/minuman.png
    - assets/images/martabak.png
    - assets/images/sate.png
    - assets/images/nasgor.png
    - assets/images/es_jeruk.png
